version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 5433
      DB_USERNAME: airflow
      DB_PASSWORD: airflow
      DB_NAME: mek
