version: '3.8'

services:
  app:
    build: .
    ports:
      - '4000:4000'
    networks:
      - airflow_network
    environment:
      DB_HOST: airflow-postgres
      DB_PORT: 5432
      DB_USERNAME: airflow
      DB_PASSWORD: airflow
      DB_NAME: mek

networks:
  airflow_network:
    name: airflow_network
    external: true